---
title: "case_study"
author: "zhuolun"
date: "10/15/2021"
output: github_document
---

```{r setup}
library(tidyverse)
library(p8105.datasets)
library(leaflet)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## load a dataset

```{r}
data("nyc_airbnb")
```

* Is price correlated with review score?
* which neighborhood is most popular? most expensive?
* is availability has the highest reviews?
* is room type related to neighborhood?
* is length of stay related to neighborhood group (borough) ?

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(borough = neighbourhood_group)
``` 

let's try to count things:
```{r}
nyc_airbnb %>% 
  count(borough,room_type) %>% 
  pivot_wider(
    names_from =  room_type,
    values_from = n 
  )
```

```{r}
nyc_airbnb %>% 
  janitor::tabyl(borough,room_type) ### the result is the same as above
```

Let's look at price and room type 
```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price)) +
  geom_point() + 
  facet_grid(. ~ room_type)

```

price and neighborhood 
```{r}
nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  group_by(neighbourhood) %>% 
  summarize(mean_price = mean(price, na.rm = TRUE)) %>% 
  arrange(mean_price)

nyc_airbnb %>% 
  filter(borough == "Manhattan",
         price <= 1000) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  ggplot(aes(x = neighbourhood, y = price)) +
  geom_boxplot() +
  coord_flip() +
  facet_grid(. ~ room_type)
```

price vs location 
```{r}
nyc_airbnb %>% 
  filter(price < 500) %>% 
  sample_n(5000) %>% 
  ggplot(aes(x = lat, y = long, color = price)) + 
  geom_point()

```

## retry leaflet
```{r,eval = FALSE}
nyc_airbnb %>% 
  leaflet() %>% 
  addTiles() %>% 
  addMarkers(~lat, ~long)  


```

